Repository EGC-Porra-23-24/porra-hub, pull requests merged in 2024-12, with the labels that each got.

#38 Filtrado por métricas de los modelos
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/templates/explore/index.html
Labels: feature

#41 Fix/arreglar download all
  app/modules/dataset/routes.py
Labels: fix

#63 fix(explore): Arreglar límite superior del filtro de fecha de creación
  app/modules/explore/repositories.py
Labels: fix, Review effort [1-5]: 1

#53 Tests verificación de email para selenium
  app/modules/auth/tests/test_selenium.py
Labels: test

#64 Arreglar botón de vaciar filtros
  app/modules/explore/assets/scripts.js
Labels: fix, Review effort [1-5]: 1

#50 test(dataset): Añadido test de Selenium
  app/modules/dataset/tests/test_selenium.py
Labels: test

#71 DSMetrics no se calcula correctamente con archivos que usa espacios
  app/modules/dataset/services.py
Labels: fix, Review effort [1-5]: 1

#74 Implementacion de nuevo workflow formateador
  .github/workflows/formatter.yml
  .github/workflows/lint.yml
Labels: Review effort [1-5]: 3

#83 Poblar base de datos al desplegar render
  .github/workflows/ci-cd-pipeline.yml
  .github/workflows/render.yml
Labels: configuration, Review effort [1-5]: 2

#89 Wokflow de render requiere python 3.11 o superior
  .github/workflows/ci-cd-pipeline.yml
Labels: fix, Review effort [1-5]: 1

#87 Cambiar ruta del home en fakenodo
  app/modules/fakenodo/routes.py
Labels: Review effort [1-5]: 1

#91 Archivos file(11-14).uvl no se pueden parsear
  app/modules/dataset/uvl_examples/file11.uvl
  app/modules/dataset/uvl_examples/file12.uvl
  app/modules/dataset/uvl_examples/file13.uvl
  app/modules/dataset/uvl_examples/file14.uvl
  app/modules/dataset/uvl_examples/file7.uvl
Labels: fix, Review effort [1-5]: 2

#94 Error en los test de Download all
  app/modules/dataset/routes.py
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/dataset/tests/test_unit_download_all.py
Labels: Review effort [1-5]: 4

#95 Workflow de render no usa la versión correcta de python
  .github/workflows/ci-cd-pipeline.yml
  .github/workflows/render.yml
Labels: fix, Review effort [1-5]: 2

#98 Cambiar entrada de secretos en workflow de despliegue en docker
  .github/workflows/deployment_on_dockerhub.yml
Labels: Review effort [1-5]: 1
